linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt

run:
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "SA1019"  # example of excluding specific issue

linters-settings:
  gofmt:
    simplify: true
