// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/LDmitryLD/testtask/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// RatesStorager is an autogenerated mock type for the RatesStorager type
type RatesStorager struct {
	mock.Mock
}

// InsertRates provides a mock function with given fields: ctx, rates
func (_m *RatesStorager) InsertRates(ctx context.Context, rates models.GetRatesResponse) error {
	ret := _m.Called(ctx, rates)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.GetRatesResponse) error); ok {
		r0 = rf(ctx, rates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRatesStorager creates a new instance of RatesStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRatesStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *RatesStorager {
	mock := &RatesStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
